version: '3.3'

services:
  #service 1: definition of mysql database
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=testtest
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./db/spade.sql:/usr/local/etc/spade.sql
      - ./db/spade-views.sql:/usr/local/etc/spade-views.sql
      - ./db/spade-config.sql:/usr/local/etc/spade-config.sql

  #service 2: definition of phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-php-myadmin
    ports:
      - "8082:80"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: testtest
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini   # add configuration due to max upload file size


  #service 3: definition of your spring-boot app
  antipatterndetection:
    image: anti-pattern-detection
    container_name: anti-pattern-detection-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"                       # spring app will starts on port 8080 (<output_port:port_inside_of_docker>)
    restart: always

    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/spade
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: testtest
      DATA_PATH: usr/local/etc/data/
    volumes:
      - ./data/:/usr/local/etc/data/
      - ./src/main/resources/application.properties:/application.properties
